set.seed(1234)

source(file = "cleanup_files.R")
source(file = "create_variables.R")
source(file = "generate_network.R")
source(file = "generate_transport.R")
source(file = "read_solution.R")
source(file = "solve_cplex.R")
source(file = "write_binaries.R")
source(file = "writeSolverFiles.R")
source(file = "write_of.R")
source(file = "write_generals.R")
source(file = "write_constraints.R")

## Case - 1
network <- generate_network(nHubs = 10, maxClinics = 10, maxDemands = 1000)
transport <- generate_transport(network = network, availabilty = c(10, 50, 200, 200))
variables <- create_variables(network = network, transport = transport)
objective_function <- write_of(transport = transport, variables = variables, network = network)
generals <- write_generals(variables = variables)
binaries <- write_binaries(variables = variables)
constraints <- write_constraints(transport = transport, variables = variables, network = network)
writeSolverFiles(oF = objective_function, binaries = binaries, constraints = constraints, generals = generals)
solve_cplex()
solution1 <- read_solution(variables = variables)
cleanup_files()

## Case - 2
network <- generate_network(nHubs = 10, maxClinics = 10, maxDemands = 10000)
transport <- generate_transport(network = network, availabilty = c(10, 50, 200, 200))
variables <- create_variables(network = network, transport = transport)
objective_function <- write_of(transport = transport, variables = variables, network = network)
generals <- write_generals(variables = variables)
binaries <- write_binaries(variables = variables)
constraints <- write_constraints(transport = transport, variables = variables, network = network)
writeSolverFiles(oF = objective_function, binaries = binaries, constraints = constraints, generals = generals)
solve_cplex()
solution2 <- read_solution(variables = variables)
cleanup_files()

## Case - 3
network <- generate_network(nHubs = 10, maxClinics = 10, maxDemands = 100000)
transport <- generate_transport(network = network, availabilty = c(10, 50, 200, 200))
variables <- create_variables(network = network, transport = transport)
objective_function <- write_of(transport = transport, variables = variables, network = network)
generals <- write_generals(variables = variables)
binaries <- write_binaries(variables = variables)
constraints <- write_constraints(transport = transport, variables = variables, network = network)
writeSolverFiles(oF = objective_function, binaries = binaries, constraints = constraints, generals = generals)
solve_cplex()
solution3 <- read_solution(variables = variables)
cleanup_files()